### ISSUE TITLE
Filter of categories in combination with showing new tracks doesnt work properly

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#222] opened 2019-04-16 12:37 UTC
When I am filtering out annotations of a catogery and I then click on «Manage tracks» followed by a click on «confirm», in the «annotation list» all annotations do appear, also the ones that in fact should be filtered out. In the timeline the filter works how it should.
![Bildschirmfoto 2019-04-16 um 14 36 59](https://user-images.githubusercontent.com/15246287/56210008-2f167b80-6055-11e9-861b-421be082866e.png)

**Comment by dagraf** [comment] 2019-08-29 06:59
Problem still exists.

**Comment by ebbertd** [comment] 2022-03-25 13:11
This seems to be fixed in the current version. Feel free to reopen this issue if you can still reproduce this.

**Closed by ebbertd** 2022-03-25 13:11 UTC
