### ISSUE TITLE
Scrubber turns colored anchors grey

### ISSUE THREAD

**Issue by Arnei** [opencast/annotation-tool#401] opened 2020-07-08 09:22 UTC
When double clicking a colored annotation in the timeline, or moving the scrubber over it, the little anchor dot turns grey until page refresh.
![Peek 2020-07-07 17-34](https://user-images.githubusercontent.com/14070005/86901384-d5441a80-c10c-11ea-90cc-f4f6ac07e69a.gif)

It seems that adding "active" to the class attribute removes the dynamically generated "category-id".

**Comment by JulianKniephoff** [comment] 2020-07-08 13:44
This is kind of a duplicate of #357. Or at least they are caused by the same thing, which should be fixed in #403.

**Closed by JulianKniephoff** 2020-07-08 13:44 UTC
