### ISSUE TITLE
Times in Timeline are confusing

### ISSUE THREAD

**Issue by rrolf** [opencast/annotation-tool#100] opened 2018-02-22 09:00 UTC
The times that are displayed in the first row of the timeline are quite confusing. 
In the default view. For a 13 minute video it is hour:minute, ie. 00:05,  which looks for me more like 5 seconds than minutes. If I zoom in it changes to seconds only at a certain zoom factor, without an indicator of the minute anymore, which is even more strange.

I would guess, that it would be okay for me at least to omit the hour (if really neccessay, but maybe reducing hours to 1 digit would or showing minutes >60 would be a better solution. And for the zoomed view an indicator of the current minute would be needed. 

![bildschirmfoto 2018-02-22 um 09 52 34](https://user-images.githubusercontent.com/1894165/36528968-2c35a040-17b7-11e8-8a02-9b46e94fd2af.png)
![bildschirmfoto 2018-02-22 um 09 53 16](https://user-images.githubusercontent.com/1894165/36528973-2f1f6fc0-17b7-11e8-994d-9f67ec634f35.png)

**Comment by JulianKniephoff** [comment] 2019-10-09 07:11
Isn't this a duplicate of #169? Or vice versa, but that one is the one I "worked with" more recently, sorry. :wink:

I'm closing this, then. If someone thinks this is a unique issue, feel free to reopen it.

**Closed by JulianKniephoff** 2019-10-09 07:11 UTC
Labels: usability
