### ISSUE TITLE
The end of a annotation can be pulled over the end of the video

### ISSUE THREAD

**Issue by dagraf** [opencast/annotation-tool#297] opened 2019-12-18 14:58 UTC
In a video lasting 2:41 a can drag the end of an annotation further than 2:41, so that e.g. 4:15 is displayed in the list of annotations.

**Comment by JulianKniephoff** [comment] 2020-01-28 13:46
This is a duplicate of #314 and will be fixed in #315

**Closed by JulianKniephoff** 2020-01-28 13:46 UTC
